### ISSUE TITLE
Add song assessment tracking

### ISSUE THREAD

**Issue by hayleybech** [hayleybech/choirconcierge-main#127]
- [ ] Add assessment status for singer (Not Started|Learning|Assessment Ready|Performance Ready)
- [ ] Add report for single song
- [ ] Add report for multiple songs (based on filter)
